-- MySQL Script generated by MySQL Workbench
-- Wed May  4 10:53:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cdweb2022
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cdweb2022
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cdweb2022` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `cdweb2022` ;

-- -----------------------------------------------------
-- Table `cdweb2022`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdweb2022`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `birthday` DATETIME NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `gender` INT(11) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `updated_date` DATETIME NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `cdweb2022`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdweb2022`.`address` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `company` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `district` VARCHAR(255) NULL DEFAULT NULL,
  `fullname` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `updated_date` DATETIME NULL DEFAULT NULL,
  `ward` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKda8tuywtf0gb6sedwk7la1pgi` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKda8tuywtf0gb6sedwk7la1pgi`
    FOREIGN KEY (`user_id`)
    REFERENCES `cdweb2022`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `cdweb2022`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdweb2022`.`category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `cdweb2022`.`attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdweb2022`.`attribute` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `value` VARCHAR(255) NULL DEFAULT NULL,
  `category_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK1eji3t1hu871hkq00mx58v7w3` (`category_id` ASC) VISIBLE,
  CONSTRAINT `FK1eji3t1hu871hkq00mx58v7w3`
    FOREIGN KEY (`category_id`)
    REFERENCES `cdweb2022`.`category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `cdweb2022`.`voucher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdweb2022`.`voucher` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `cost` BIGINT(20) NULL DEFAULT NULL,
  `ended_date` DATETIME NULL DEFAULT NULL,
  `started_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `cdweb2022`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdweb2022`.`bill` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NULL DEFAULT NULL,
  `shipping_cost` BIGINT(20) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `total` BIGINT(20) NULL DEFAULT NULL,
  `updated_date` DATETIME NULL DEFAULT NULL,
  `address_id` BIGINT(20) NULL DEFAULT NULL,
  `voucher_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK1f5an6dq4k8u0idf4oxthpf8t` (`address_id` ASC) VISIBLE,
  INDEX `FKsp8lqd3ijs9y7t59djo0y1g1c` (`voucher_id` ASC) VISIBLE,
  CONSTRAINT `FK1f5an6dq4k8u0idf4oxthpf8t`
    FOREIGN KEY (`address_id`)
    REFERENCES `cdweb2022`.`address` (`id`),
  CONSTRAINT `FKsp8lqd3ijs9y7t59djo0y1g1c`
    FOREIGN KEY (`voucher_id`)
    REFERENCES `cdweb2022`.`voucher` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `cdweb2022`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdweb2022`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `discount` INT(11) NULL DEFAULT NULL,
  `long_description` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` BIGINT(20) NULL DEFAULT NULL,
  `quantity` BIGINT(20) NULL DEFAULT NULL,
  `short_description` VARCHAR(255) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `summary` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `cdweb2022`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdweb2022`.`comment` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `star` INT(11) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `product_id` BIGINT(20) NULL DEFAULT NULL,
  `user_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKm1rmnfcvq5mk26li4lit88pc5` (`product_id` ASC) VISIBLE,
  INDEX `FK8kcum44fvpupyw6f5baccx25c` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK8kcum44fvpupyw6f5baccx25c`
    FOREIGN KEY (`user_id`)
    REFERENCES `cdweb2022`.`user` (`id`),
  CONSTRAINT `FKm1rmnfcvq5mk26li4lit88pc5`
    FOREIGN KEY (`product_id`)
    REFERENCES `cdweb2022`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `cdweb2022`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdweb2022`.`image` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(255) NULL DEFAULT NULL,
  `product_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKgpextbyee3uk9u6o2381m7ft1` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FKgpextbyee3uk9u6o2381m7ft1`
    FOREIGN KEY (`product_id`)
    REFERENCES `cdweb2022`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `cdweb2022`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdweb2022`.`order_detail` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `price` BIGINT(20) NULL DEFAULT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  `bill_id` BIGINT(20) NULL DEFAULT NULL,
  `product_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK8xyxpaxwufax0438f2rvtb2xs` (`bill_id` ASC) VISIBLE,
  INDEX `FKb8bg2bkty0oksa3wiq5mp5qnc` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK8xyxpaxwufax0438f2rvtb2xs`
    FOREIGN KEY (`bill_id`)
    REFERENCES `cdweb2022`.`bill` (`id`),
  CONSTRAINT `FKb8bg2bkty0oksa3wiq5mp5qnc`
    FOREIGN KEY (`product_id`)
    REFERENCES `cdweb2022`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `cdweb2022`.`product_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdweb2022`.`product_attribute` (
  `product_id` BIGINT(20) NOT NULL,
  `attribute_id` BIGINT(20) NOT NULL,
  INDEX `FKefc9famxhv98xs6686269a79` (`attribute_id` ASC) VISIBLE,
  INDEX `FKlefs59y5kmsbu017n1wp10gf2` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FKefc9famxhv98xs6686269a79`
    FOREIGN KEY (`attribute_id`)
    REFERENCES `cdweb2022`.`attribute` (`id`),
  CONSTRAINT `FKlefs59y5kmsbu017n1wp10gf2`
    FOREIGN KEY (`product_id`)
    REFERENCES `cdweb2022`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `cdweb2022`.`response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdweb2022`.`response` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `comment_id` BIGINT(20) NULL DEFAULT NULL,
  `user_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKjo7d296slarpmfr8p3oeqlsx2` (`comment_id` ASC) VISIBLE,
  INDEX `FKo86so3ptvukgyfb2rkb63hab4` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKjo7d296slarpmfr8p3oeqlsx2`
    FOREIGN KEY (`comment_id`)
    REFERENCES `cdweb2022`.`comment` (`id`),
  CONSTRAINT `FKo86so3ptvukgyfb2rkb63hab4`
    FOREIGN KEY (`user_id`)
    REFERENCES `cdweb2022`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `cdweb2022`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdweb2022`.`role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `cdweb2022`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdweb2022`.`user_role` (
  `user_id` BIGINT(20) NOT NULL,
  `role_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `FKa68196081fvovjhkek5m97n3y` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FK859n2jvi8ivhui0rl0esws6o`
    FOREIGN KEY (`user_id`)
    REFERENCES `cdweb2022`.`user` (`id`),
  CONSTRAINT `FKa68196081fvovjhkek5m97n3y`
    FOREIGN KEY (`role_id`)
    REFERENCES `cdweb2022`.`role` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
